apiVersion: v1
kind: ConfigMap
metadata:
  name: composer-ndots-configmap
  namespace: egs-conv
data:
  resolv.conf: |
    options ndots:1
    nameserver 10.43.0.10
    nameserver 8.8.4.4
    nameserver 8.8.8.8
    nameserver 192.168.227.21
    nameserver 192.168.227.20
    search ua.pt egs-conv.svc.cluster.local svc.cluster.local cluster.local deti

