apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversion-deployment
  namespace: egs-conv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversion-deployment
  template:
    metadata:
      labels:
        app: conversion-deployment
    spec:
      containers:
      - name: conversion-deployment
        image: registry.deti:5000/egs-conv/conversion-service:latest
        env:
          - name: PYTHONPATH
            value: /home/app
        envFrom:
          - secretRef:
              name: activemq-secrets
          - configMapRef:
              name: activemq-configmap
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: ndots-vol
            mountPath: /etc/resolv.conf
            subPath: resolv.conf
      volumes:
        - name: ndots-vol
          configMap:
            name: conversion-ndots-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: conversion-service
  namespace: egs-conv
spec:
  ports:
  - name: http
    port: 80 # Required Value, not used
  selector:
    app: conversion-deployment
---