---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: egs-conv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-deployment
  template:
    metadata:
      labels:
        app: web-deployment
    spec:
      containers:
      - name: web-deployment
        image: registry.deti:5000/egs-conv/web-service:latest
        env:
          - name: REACT_APP_PROXY_URL
            value: http://egs-conv.deti
          - name: REACT_APP_COOKIE_NAME
            value: MY_SUPER_COOOKIE
          - name: REACT_APP_COOKIE_DOMAIN
            value: .egs-conv.deti
          - name: WDS_SOCKET_PORT
            value: "0"
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        volumeMounts:
          - name: ndots-vol
            mountPath: /etc/resolv.conf
            subPath: resolv.conf
      volumes:
        - name: ndots-vol
          configMap:
            name: web-ndots-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: egs-conv
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: web-deployment
---
# cheat sheet
# nc -zvv composer-service.egs-conv.svc.cluster.local 80
